// Copyright 2023 Scan Line
// https://github.com/scan-line

// This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

#define ENABLE_RGB_MATRIX_SLOWDROPS

// Matrix off is always enum 0
// Matrix solid color is always enum 1
// Include order defines remaining enum order
#include "slowdrops_anim.h"

#undef ENABLE_RGB_MATRIX_SLOWDROPS
